"""Dash Kaleido - Powerful layout and tab management for Dash applications."""

import json
import os as _os
import sys as _sys

import dash as _dash

# Import components from auto-generated modules
from ._imports_ import *  # noqa: F401, F403
from ._imports_ import __all__ as _components

# Import decorators for layout registration
from .decorators import register_layout_callback

# Import layout registry utilities
from .layout_registry import register_layout, get_registered_layouts_metadata

# Import layout transformation utilities
from .layout_utils import walk_layout, inject_tab_id

# Module imports trigger a dash.development import, need to check this first
if not hasattr(_dash, "__plotly_dash") and not hasattr(_dash, "development"):
    print(
        "Dash was not successfully imported. Make sure you don't have a file "
        "named \n'dash.py' in your current directory.",
        file=_sys.stderr,
    )
    _sys.exit(1)

_basepath = _os.path.dirname(__file__)
_filepath = _os.path.abspath(_os.path.join(_basepath, "package-info.json"))
with open(_filepath) as f:
    package = json.load(f)

package_name = package["name"].replace(" ", "_").replace("-", "_")
__version__ = package["version"]

_current_path = _os.path.dirname(_os.path.abspath(__file__))

# JavaScript distribution files
_js_dist = [
    {
        "relative_package_path": "dash_kaleido.min.js",
        "namespace": package_name,
    },
    {
        "relative_package_path": "dash_kaleido.min.js.map",
        "namespace": package_name,
        "dynamic": True,
    },
]

# Runtime prop validation for development (auto-generated by dash-generate-components)
_js_dist.append({
    "dev_package_path": "proptypes.js",
    "dev_only": True,
    "namespace": package_name,
})

# CSS distribution files (none for now)
_css_dist = []

# Attach distribution info to all components
for _component in _components:
    setattr(locals()[_component], "_js_dist", _js_dist)
    setattr(locals()[_component], "_css_dist", _css_dist)

# Public API exports
__all__ = list(_components) + [
    "register_layout",
    "register_layout_callback",
    "get_registered_layouts_metadata",
    "walk_layout",
    "inject_tab_id",
    "render_layout_for_tab",
    "init",
]


def init(app, kaleido_id: str):
    """
    Initialize Kaleido callbacks. Must be called after app.layout is set.
    
    This function automatically:
    - Populates the KaleidoManager's registeredLayouts with metadata from the registry
    - Creates a callback to render layout content based on activeTabData
    - Static layouts are returned immediately (already in memory)
    - Lazy/callable layouts are evaluated on-demand
    - For allow_multiple=True layouts, component IDs are transformed to pattern-matching format
    
    Parameters
    ----------
    app : dash.Dash
        The Dash application instance
    kaleido_id : str
        The ID of the KaleidoManager component
    
    Examples
    --------
    >>> app.layout = html.Div([
    ...     dash_kaleido.KaleidoManager(id='kaleido', ...)
    ... ])
    >>> dash_kaleido.init(app, 'kaleido')
    """
    from dash import Input, Output, html
    from .layout_registry import LayoutRegistry
    from .layout_utils import inject_tab_id
    
    # Import components locally to avoid circular imports
    from .KaleidoTab import KaleidoTab
    
    # Traverse the app.layout to find and update the KaleidoManager component
    def update_component(component):
        if hasattr(component, 'id') and component.id == kaleido_id:
            # Inject the registered layouts metadata
            component.registeredLayouts = get_registered_layouts_metadata()
            return True
        if hasattr(component, 'children'):
            children = component.children
            if isinstance(children, list):
                for child in children:
                    if update_component(child):
                        return True
            elif children:
                return update_component(children)
        return False
    
    if app.layout:
        update_component(app.layout)
    
    # Create the rendering callback using tabsData for all tabs with layouts
    # This returns KaleidoTab components for each tab, enabling client-side tab switching
    @app.callback(
        Output(kaleido_id, 'children'),
        Input(kaleido_id, 'tabsData'),
        prevent_initial_call=True
    )
    def _kaleido_render_all_tabs(tabs_data):
        """Render layout content for all tabs that have a layout selected.
        
        Returns a list of KaleidoTab components, one per tab with a layout.
        The KaleidoManager handles visibility toggling on the client side.
        """
        if not tabs_data:
            return []
        
        tab_components = []
        
        for tab_info in tabs_data:
            tab_id = tab_info.get('id')
            layout_id = tab_info.get('layoutId')
            layout_params = tab_info.get('layoutParams') or {}
            
            if not tab_id or not layout_id:
                continue
            
            # Resolve the layout (static or lazy)
            layout_info = LayoutRegistry.get_layout(layout_id)
            if not layout_info:
                tab_components.append(
                    KaleidoTab(
                        id={'type': 'kaleido-tab-content', 'index': tab_id},
                        children=html.Div([
                            html.H3('Layout not found'),
                            html.P(f"Layout '{layout_id}' is not registered.")
                        ])
                    )
                )
                continue
            
            layout = layout_info['layout']
            
            # Call if it's a callable (lazy layout)
            if callable(layout):
                # Check if the layout accepts parameters
                params = layout_info.get('parameters', [])
                if params and layout_params:
                    # Build kwargs from layoutParams, using defaults where needed
                    kwargs = {}
                    for param_info in params:
                        param_name = param_info['name']
                        if param_name in layout_params and layout_params[param_name]:
                            kwargs[param_name] = layout_params[param_name]
                        elif param_info['has_default']:
                            kwargs[param_name] = param_info['default']
                        # If required and not provided, pass empty string
                        else:
                            kwargs[param_name] = ''
                    layout = layout(**kwargs)
                else:
                    layout = layout()
            
            # If allowMultiple, inject tab IDs into component IDs
            if layout_info.get('allow_multiple', False):
                layout = inject_tab_id(layout, tab_id)
            
            # Wrap in KaleidoTab with pattern-matching ID
            # Include layoutId in the index to force React to re-render when layout changes
            tab_components.append(
                KaleidoTab(
                    id={'type': 'kaleido-tab-content', 'index': f"{tab_id}:{layout_id}"},
                    children=layout
                )
            )
        
        return tab_components


def render_layout_for_tab(active_tab_data: dict):
    """
    Helper to render the correct layout for a tab, automatically handling
    ID injection for allow_multiple layouts and passing parameters to layout functions.
    
    This is a convenience function for users who want to write their own
    callback instead of using dash_kaleido.init().
    
    Parameters
    ----------
    active_tab_data : dict
        The activeTabData from KaleidoManager, containing:
        - id: Unique tab UUID
        - layoutId: The layout ID to render
        - name: Tab display name
        - createdAt: Unix timestamp
        - layoutParams: Dict of parameter values (optional)
    
    Returns
    -------
    Component or None
        The rendered layout, or None if no layout selected
    
    Examples
    --------
    >>> from dash import callback, Input, Output
    >>> import dash_kaleido
    >>> 
    >>> @callback(
    ...     Output('kaleido-manager', 'children'),
    ...     Input('kaleido-manager', 'activeTabData')
    ... )
    ... def render_content(tab_data):
    ...     return dash_kaleido.render_layout_for_tab(tab_data)
    """
    from dash import html
    from .layout_registry import LayoutRegistry
    from .layout_utils import inject_tab_id
    
    if not active_tab_data or not active_tab_data.get('layoutId'):
        return None
    
    layout_id = active_tab_data['layoutId']
    tab_id = active_tab_data['id']
    layout_params = active_tab_data.get('layoutParams') or {}
    
    layout_info = LayoutRegistry.get_layout(layout_id)
    if not layout_info:
        return html.Div(f"Layout '{layout_id}' not found")
    
    layout = layout_info['layout']
    
    # Call if it's a callable (lazy layout)
    if callable(layout):
        # Check if the layout accepts parameters
        params = layout_info.get('parameters', [])
        if params and layout_params:
            # Build kwargs from layoutParams, using defaults where needed
            kwargs = {}
            for param_info in params:
                param_name = param_info['name']
                if param_name in layout_params and layout_params[param_name]:
                    kwargs[param_name] = layout_params[param_name]
                elif param_info['has_default']:
                    kwargs[param_name] = param_info['default']
                else:
                    kwargs[param_name] = ''
            layout = layout(**kwargs)
        else:
            layout = layout()
    
    # If allowMultiple, inject tab IDs into component IDs
    if layout_info.get('allow_multiple', False):
        layout = inject_tab_id(layout, tab_id)
    
    return layout
