// AUTOGENERATED FILE - DO NOT EDIT

var pt = window.PropTypes;
var pk = window['dash_kaleido'];

pk.DashKaleido.propTypes = {label:pt.string,
 value:pt.oneOfType([pt.string]),
 id:pt.oneOfType([pt.string]),
 setProps:pt.any};
pk.KaleidoManager.propTypes = {style:pt.any,
 activeTab:pt.oneOfType([pt.string]),
 activeTabData:pt.oneOfType([pt.object]),
 tabs:pt.oneOfType([pt.arrayOf(pt.object)]),
 registeredLayouts:pt.oneOfType([pt.object]),
 displayedLayouts:pt.oneOfType([pt.arrayOf(pt.string)]),
 initialTab:pt.oneOfType([pt.string]),
 theme:pt.oneOfType([pt.string]),
 enableStatusBar:pt.any,
 searchBarConfig:pt.oneOfType([pt.object]),
 contentOverflow:pt.oneOfType([pt.string]),
 maxTabs:pt.oneOfType([pt.number]),
 persistence:pt.oneOfType([pt.string,pt.number]),
 persisted_props:pt.oneOfType([pt.arrayOf(pt.string)]),
 persistence_type:pt.oneOfType([pt.string]),
 loading_state:pt.oneOfType([pt.object]),
 children:pt.node,
 tabsData:pt.oneOfType([pt.arrayOf(pt.object)]),
 id:pt.oneOfType([pt.string]),
 setProps:pt.any};
pk.KaleidoTab.propTypes = {children:pt.node,
 style:pt.any,
 className:pt.oneOfType([pt.string]),
 loading_state:pt.oneOfType([pt.shape({is_loading:pt.any,prop_name:pt.oneOfType([pt.string]),component_name:pt.oneOfType([pt.string])})]),
 id:pt.oneOfType([pt.string]),
 setProps:pt.any};
